apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-2204-containerdisk
  namespace: default
  labels:
    kubevirt.io/vm: ubuntu-2204-containerdisk
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk-os
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
        machine:
          type: q35
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 2
            memory: 2Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - containerDisk:
            image: gcr.io/spectro-images-public/release/vm-dashboard/os/ubuntu-container-disk:22.04
          name: containerdisk-os
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              ssh_pwauth: True
              chpasswd: { expire: False }
              password: spectro
              disable_root: false
              runcmd:
                - apt-get update
                - apt-get install -y qemu-guest-agent
                - systemctl start qemu-guest-agent
          name: cloudinitdisk